[project]
name = "rpa-flow-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "pyinstaller>=6.14.0",
    "sse-starlette>=2.3.6",
    "uvicorn>=0.34.3",
]
